### ISSUE TITLE
Finish tying in process_labels code to create_iq_snapshot (integrate using python not shell scripts)

### ISSUE THREAD

**Issue by mikeaintworkin** [thisaintwork/iqss_gh_reporting#27]
The objective here is to eliminate the use of a shell script to integrate ceilyn's code that creates the matrix into a normal run.
This is a basic integration as part of the V1.0 MVP. 
It's OK if the code is not clean, as long as it  is bug free.

**Comment by mikeaintworkin** [comment]
Example of the current state of the integration.

```
create_iq_snapshot_init \
     --collection_flag "snapshot" \
     --collection_timestamp "" \
     --sprint_name "20230503sprint" \
     --src_dir_name "" \
     --src_file_name "" \
     --organization_name "IQSS" \
     --project_name "IQSS/dataverse" \
     --src_type "api"\
     --workflow_name "tst"


# 
# usage: process_labels.py [-h] --input INPUT --output OUTPUT [--matrix MATRIX]
# process_labels.py: error: the following arguments are required: --input, --output
# perftest@ubuntu:~/DevCode/github-com-mreekie/iqss_gh_reporting$
DIRNAME=/home/perftest/iqss_gh_reporting/run/out/April_26_2023_sprint-end
INFILE=2023_05_10-14_37_49-April262023-end-create_iq_snapshot-api-20230510143749-sized.tsv
INFILECORE=$(echo "${INFILE}" | cut -d'-' -f1-7)


OUTFILE="${INFILECORE}-matrix_summary .tsv"
MATRIXFILE="${INFILECORE}-matrix.tsv"

cat<<EOF
${DIRNAME}
${INFILE}
${INFILECORE}
${OUTFILE}
${MATRIXFILE}
cp ${DIRNAME}/${INFILE} ${DIRNAME}/input.tsv

EOF

cp "${DIRNAME}/${INFILE}" "${DIRNAME}/input.tsv"

process_labels --input "${DIRNAME}/input.tsv" --output "${DIRNAME}/outputput.tsv" --matrix "${DIRNAME}/matrix.tsv"

cp  "${DIRNAME}/outputput.tsv" "${DIRNAME}/${OUTFILE}"
cp "${DIRNAME}/matrix.tsv" "${DIRNAME}/${MATRIXFILE}"
```

**Comment by mikeaintworkin** [comment]
Here's the dev/test loop for  this:
in pycharm in the run configuration:
set working directory:
- /home/perftest/DevCode/github-com-mreekie/iqss_gh_reporting/scripts
set the GITHUB_TOKEN
```
cd /home/perftest/DevCode/github-com-mreekie/iqss_gh_reporting/scripts
./workflow-May032023sprint-snapshot.sh 

```
the input_file.yaml is now in scripts directory
Start the debugger for iqss_gh_reporting

Run create_iq_snapshot in debug mode

**Comment by mikeaintworkin** [comment]
OK, now I'll try this built locally.

make change to create_iq_snapshot in project: iqss_gh_reporting
cd ~/DevCode/github-com-mreekie/iqss_gh_reporting
bash -cl "/usr/bin/python3.10 /home/perftest/DevCode/github-com-mreekie/iqss_gh_reporting/setup.py bdist_wheel"; pip install .
pushd /home/perftest/DevCode/github-com-mreekie/iqss_gh_reporting/scripts
./workflow-May032023sprint-snapshot.sh
create_iq_snapshot
popd

**Comment by mikeaintworkin** [comment]
Test the checkin from the repo

Switch to the "builds" project.
Update it from github
cd ~/DevCode/github-com-mreekie/builds
bash -cl "/usr/bin/python3.10 /home/perftest/DevCode/github-com-mreekie/iqss_gh_reporting/setup.py bdist_wheel"; pip install .
pushd /home/perftest/DevCode/github-com-mreekie/iqss_gh_reporting/scripts
./workflow-May032023sprint-snapshot.sh
create_iq_snapshot
popd

**Comment by mikeaintworkin** [comment]
I'm going to leave this issue open for now since this was just a cursory check.
This issue is ready for Ceilyn to give it a shot and I guess that would act as our informal review and QA.

**Comment by mikeaintworkin** [comment]
Ceilyn and I looked at this today.
The last piece left to this is transition away from her code reading from a file for the first step and instead just taking the already present dataframe.

```
   xfmrd_df = xfmr.SprintCardSizer(sprint_data).df
    sprint_data.df = xfmrd_df
    sprint_data.write(postfix="sized")

    summarized_data = xfmr.SprintSizeSummarizer(sprint_data)

    # read the input file
    # Todo: This does not need to be read. The data frame can be passed in.
    snapshot_file = sprint_data.dest_dir_name + "/" + sprint_data.dest_file_name + "-sized.tsv"
    df = plu.read_sized_snapshot(snapshot_file)

```

**Comment by mikeaintworkin** [comment]
Ran into this.


```
Traceback (most recent call last):
File "/home/perftest/.local/bin/create_iq_snapshot", line 168, in <module>
main()
File "/home/perftest/.local/bin/create_iq_snapshot", line 111, in main
new_df = plu.process_sized_snapshot(sprint_data.df, labels='Labels', key='CardURL')
File "/home/perftest/.local/lib/python3.10/site-packages/iqss_gh_reporting/process_labels_util.py", line 137, in process_sized_snapshot
val = _parse_labels(label_str)
File "/home/perftest/.local/lib/python3.10/site-packages/iqss_gh_reporting/process_labels_util.py", line 62, in _parse_labels
label_list = labels.split(',')
AttributeError: 'list' object has no attribute 'split'
```

**Comment by mikeaintworkin** [comment]
At line 136, it assumes the labels are expressed as a comma separated string.
This is safe when they are read from a file.

```
        if (label_str):
            val = _parse_labels(label_str)
            parsed_labels[key_value] = val
``


147 legacy.py
- I'll ensure that this value is stored as a string when the data is collected.
- This appears to have resolved the issue.

```
                        RequiredDfColumnHeaderNames.value("labels"): str(card_content.labels),
```

**Comment by mikeaintworkin** [comment]
Also turned up an issue in pdata.py while looking.
- I was overly aggressive in cleaning strings for directory paths.
- I was turning - into _ 

Fixed in line 55

```
'out_dir':  sanitize_filepath(dest_dir_name + '/' + sprint_name, platform="auto"),
```

**Comment by cmbz** [comment]
I can also add a check to _parse_labels to throw a useful exception if the labels are not structured as comma separated strings.

**Comment by mikeaintworkin** [comment]
> I can also add a check to _parse_labels to throw a useful exception if the labels are not structured as comma separated strings.

I think we're good here for the MVP.
We should take that into account in the next rev though. It's been years too long, but I think something like this falls under the concept of a contract or something?  Everyone agrees on how data is represented, etc?  Not sure.

**Comment by mikeaintworkin** [comment]
I'm closing this.
Looking back at our short list objectives in the description, I think they are met.
